Select group by criteria
t-cheepeng/time-tracker-visualizer pull request #1
Opened 2021-06-14 17:21 UTC by garylyp

Changes

- Allow selection of two Group By critieria via dropdowns 
![image](https://user-images.githubusercontent.com/41105221/121932576-989a8d80-cd77-11eb-8af3-d7dc04b509fc.png)

- Upload box turns green upon successful upload
![image](https://user-images.githubusercontent.com/41105221/121932706-bff15a80-cd77-11eb-8a63-e805087cee18.png)

- Reset button (kinda redundant. I didn't realized you can just re-upload another file right away) [clears the green background, clears the figure at the bottom)
![image](https://user-images.githubusercontent.com/41105221/121932810-e4e5cd80-cd77-11eb-9c69-d2f5baeee9b9.png)

2021-06-14 17:22 UTC, garylyp commented on src/app.py
> +    return 'placeholder'
probably need a better way to iterate this. But next time

2021-06-14 17:25 UTC, garylyp commented on src/app.py
> +                {'label': 'Date', 'value': 'Date'},
- probably can store these options elsewhere in a Constants script
- need to disable certain options (if already selected in the first criteria box) or can trigger a pop-up if attempting to sort by the same label
- maybe it's more logical to 1) Perform the upload first, 2) provide the list of columns the user can sort by

2021-06-14 17:26 UTC, garylyp commented on src/app.py
> +    html.Hr(id='placeholder'),
Because all callbacks must have an output field. This is for `update_critieria`

2021-06-15 01:08 UTC, t-cheepeng commented
I think you were working on an older copy. Please help resolve the merge conflicts. Thanks 👍

2021-06-15 01:26 UTC, t-cheepeng requested changes

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +upload_data_style = {
If you wish to extract out the style, it would be good to put it in a `.css` file in `assets` folder and add that as a class to the Upload

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +        "Group By: ",
If there are text characters, it is a good practice to place it in a `<span>` tag (`html.Span`)

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +                {'label': '(None)', 'value': '(None)'},
Purpose of the (None)?

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +                {'label': 'Date', 'value': 'Date'},
- can have a `const.py` or something to store constant

- yes to the third point. You can take it one step further by making the second criteria only appear if the first criteria has been selected

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +    style={
Good that you are styling up the components from the get go. We are using bootstrap here so you can actually use the classes provided to style the components. It is a lot cleaner that way.

e.g. `display: flex` can be replaced by `d-flex`. or you could wrap the whole chunk in a `dbc.Row` components

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +criteria = [None] * 10
Why is there a global variable here? Let's scope our variables as close as possible and avoid any global ones if possible

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +            return html.H4(['There was error processing the file uploaded or the file was empty.']), upload_data_style
Let's keep it consistent and state that this is an array too

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +        for i in range(len(criteria)):
In the updated codebase, you can probably place this into the `services` folder

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +        return output_data_upload_children, upload_data_style2
As above

2021-06-15 01:26 UTC, t-cheepeng commented on src/app.py
> +    changed_id = [p['prop_id'] for p in dash.callback_context.triggered][0]
Is it possible to place the `upload-data` style over into this callback? Potentially cleaner code if you do that. You can have the reset button be placed in another `div` if required

2021-06-15 01:28 UTC, t-cheepeng commented
Why does the `reset` button look so weird? Can you check if bootstrap has been attached to your dev server? Thanks!

2021-06-15 06:17 UTC, garylyp commented on src/app.py
> +                {'label': '(None)', 'value': '(None)'},
was following the dropdown options from the clockify app itself
![image](https://user-images.githubusercontent.com/41105221/122002461-58bdbf80-cde4-11eb-84ba-e2503aa51892.png)

2021-06-15 06:18 UTC, garylyp commented on src/app.py
> +    style={
ohh okay i have no idea what to use, guess think i will try row

2021-06-15 06:19 UTC, garylyp commented on src/app.py
> +criteria = [None] * 10
wondering how to pass the data into the other callback. will try replacing it with smth

2021-06-15 06:19 UTC, garylyp commented on src/app.py
> +            return html.H4(['There was error processing the file uploaded or the file was empty.']), upload_data_style
oh like return a list?

2021-06-15 06:20 UTC, garylyp commented on src/app.py
> +        for i in range(len(criteria)):
okayy

2021-06-15 15:21 UTC, garylyp commented on src/app.py
> +        "Group By: ",
excellent idea. You are damn smart

2021-06-15 15:23 UTC, garylyp commented on src/app.py
> +    style={
where can i find what is made available by the bootstrap?

2021-06-15 17:23 UTC, garylyp commented on src/app.py
> +upload_data_style = {
not too sure how css works, leaving this out first

2021-06-15 17:25 UTC, garylyp commented
> Why does the `reset` button look so weird? Can you check if bootstrap has been attached to your dev server? Thanks!

Not too sure what that means (bootstrap has been attached to your dev server), but i am leaving the reset button out for now. Got quite a bit of changes already in the current PR

2021-06-16 01:22 UTC, t-cheepeng approved these changes

2021-06-16 01:22 UTC, t-cheepeng commented on src/assets/constants.py
> +# TODO: Generate the list of dictionaries (below) automatically from the list of criteria
there's actually a special meaning to the `assets` folder in dash apps. They are mainly to hold `.css` files used for styling and the dash framework automatically loads styles from that folder so try not to place `.py` files here. You can place constants in a constants folder. or just in root since its going to be used everywhere

2021-06-16 01:23 UTC, t-cheepeng commented
Will merge in code for now and change the structure of files as per comment later

2021-06-16 01:23 UTC, merged

2021-06-16 01:25 UTC, t-cheepeng commented on src/app.py
> +    style={
Official bootstrap components: https://getbootstrap.com/docs/5.0/components/accordion/

DBC components: https://dash-bootstrap-components.opensource.faculty.ai/docs/components/alert/

DBC builds on top of official bootstrap but does not implement all components of bootstrap itself. If you cannot find the component you want from dbc, then use bootstrap

2021-06-16 01:25 UTC, t-cheepeng commented on src/app.py
> +            return html.H4(['There was error processing the file uploaded or the file was empty.']), upload_data_style
yes

2021-06-16 01:28 UTC, t-cheepeng commented
> Not too sure what that means (bootstrap has been attached to your dev server)

Just means whether the bootstrap files are being served to the local server at `127.0.0.1`. You can check this by using the developer console and seeing if there is a request made to a CDN with bootstrap in the name or just checking if the `class="row"` has styling attached to the class

In either case, from your screenshots, it looks like the components are styled (e.g. dropdown list, etc...) 
But I think you did not style the reset button with `class="btn btn-primary"` or something similar, that's why it looks weird